name: Build EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --windowed --hidden-import=plyer.platforms.win.notification --name pc-remote server.py
      
      - name: Move config.yaml to dist
        run: copy config.yaml dist\

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pc-remote
          path: |
            dist/pc-remote.exe
            dist/config.yaml
      
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          name: pc-remote v1.0.0
          body: "First official release with packaged EXE and config."
          files: pc-remote.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

