name: Build EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --windowed --hidden-import=plyer.platforms.win.notification --name pc-remote server.py
      
      - name: Move config.yml to dist
        run: copy config.yml dist\

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pc-remote
          path: |
            dist/pc-remote.exe
            dist/config.yaml
